### ISSUE TITLE
Use is_terminal from std lib?

### ISSUE THREAD

**Issue by jcamiel** [colored-rs/colored#141]
Hi, 
In Rust 1.70, `is_terminal` is available on `std::io::stdout()/stderr()/stdin()`, maybe this is an opportunity to remove the `atty` dependency?

In [/colored/src/control.rs](https://github.com/colored-rs/colored/blob/master/src/control.rs) instead of:

```rust
ShouldColorize {
            clicolor: ShouldColorize::normalize_env(env::var("CLICOLOR")).unwrap_or(true)
                && atty::is(atty::Stream::Stdout),
```

The code can be now:

```rust
ShouldColorize {
            clicolor: ShouldColorize::normalize_env(env::var("CLICOLOR")).unwrap_or(true)
                && std::io::stdout().is_terminal(),
```

I can make a PR if needed!

Thanks,

**Comment by jcamiel** [comment]
Ah sorry, I didn't check PR (#134), fill free to close mine!

**Comment by hwittenborn** [comment]
This is actually being discussed in https://github.com/colored-rs/colored/pull/122 as well, an MSRV just needs to be decided on before figuring out if a crate or the stdlib will be used.

Feel free to track the issue linked in that PR for any updates :)
