### ISSUE TITLE
Switch to std::io::IsTerminal for v3

### ISSUE THREAD

**Issue by kurtlawrence** [colored-rs/colored#144]
For the `v3` release, switch to using `std::io::IsTerminal`.

**Comment by juntyr** [comment]
+1 from me for removing the atty dependency

**Comment by Oakchris1955** [comment]
I opened a PR (#149) which uses the built-in trait instead of the external crate. I hope it get approved by the maintainers

**Comment by hwittenborn** [comment]
Thanks for the PR @Oakchris1955! I'll get that merged in once the v3 branch gets created - there's a few other PRs that need to get merged, and then I'll get that looked at.

**Comment by Oakchris1955** [comment]
Since this was basically resolved with `2.1`, shouldn't this issue be closed?
