### ISSUE TITLE
Changelog does not include version 2.1.0 yet

### ISSUE THREAD

**Issue by hasezoey** [colored-rs/colored#162]
I was just upgrading this package and wanted to consult the CHANGELOG, but noticed that 2.1.0 has not been added yet (only `2.0.4` and `Unreleased` are present) and i am not sure which of the `Unreleased` things are for 2.1.0 or after.

**Comment by kurtlawrence** [comment]
I've added changelog notes for 2.1.0 =)
There is also release notes on the release page https://github.com/colored-rs/colored/releases/tag/v2.1.0
