### ISSUE TITLE
Move away from lazy_static

### ISSUE THREAD

**Issue by xTachyon** [colored-rs/colored#163]
Is there a plan to move away from `lazy_static`? This seems to pull an ancient version of `spin` that, at least for me, results in a duplicated dependency.

I think the new way of doing this is through `OnceLock`, which conveniently is introduced in 1.70, which is the MSRV for this crate.

**Comment by kurtlawrence** [comment]
Hi @xTachyon! We would welcome the change if you would like to raise a PR :smile:

**Comment by RuboGubo** [comment]
should this issue be open?

**Comment by spenserblack** [comment]
Looks like #164 *intended* to close this, but unfortunately (and somewhat surprisingly) "solves" isn't one of the keywords that GitHub picks up. "***re***solves" is, though 🙂
