### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by spenserblack** [colored-rs/colored#185]
Looks like users are looking forward to a new release (https://github.com/colored-rs/colored/issues/182#issuecomment-2476525953). Making this issue as a personal to-do. I'll leave this up for a while (until the end of the month feels reasonable) to give other maintainers a chance to chime in.

## To do

- [ ] Review changes since last release and update version

**Comment by kurtlawrence** [comment]
Fine with me =)

**Comment by king-11** [comment]
happy holidays, probably release can be done now 😀 we crossed end of month
