### ISSUE TITLE
Occasionally freezing forever on println!("{}", "You: ".truecolor(0, 255, 0));

### ISSUE THREAD

**Issue by sloganking** [colored-rs/colored#188]
As seen here:

https://github.com/sloganking/quick-assistant/issues/21#issuecomment-2544656813

One of my programs has a heisenbug where it occasionally freezes until I click on the terminal and press ctrl-c at which point it resumes normal execution. The freeze is consistently on this line:

```rust
println!("{}", "You: ".truecolor(0, 255, 0));
```

The bug is difficult to reproduce, but happens occasionally, and is consistently happening on this specific line of code. Could the `.truecolor(0, 255, 0)` function be causing a freeze? What I've narrowed it down to is the freezes either occurring inside the `truecolor()` function itself or inside the `println!()` macro when it is handed the data from `truecolor()`. 

The next time my program freezes, I will know if the freeze is inside the `truecolor()` function itself, but neither outcome are ideal behavior or good for the functioning of this library. 

My `cargo.lock` is using 
```
name = "colored"
version = "2.1.0"
```

And thus far, I've been running my program using Windows `command prompt`.

**Comment by spenserblack** [comment]
A few questions:

1. If you intentionally click inside of Command Prompt during your test runs, does the issue become more consistent?
2. If you use a different terminal, like Windows Terminal, does this stop happening?
3. Does this explain the issue? https://stackoverflow.com/a/33883532

**Comment by sloganking** [comment]
@spenserblack 

> https://stackoverflow.com/a/33883532

Well, this is embarrassing. My old screenshots from the original freezing don't contain the title of the terminal window, so I can't see if select was in front of the command or not, but this certainly seems to to be what's happening now, I'm gonna close this issue and reopen it if I find something else. Thanks for showing me select mode. I've been struggling with this issue for almost a year. What a interestingly unintuitive default terminal feature.

**Comment by spenserblack** [comment]
No problem! I'm not 100% sure that's the issue, but I can't imagine it being anything else right now. It's definitely a surprising (and not well-known AFAIK) feature, so no embarrassment 🙂
